### PR TITLE
Plonk zexe

### PR DESCRIPTION
**Pull request by vlopes11**

### CODE REVIEW

**Comment by CPerezz** [comment]
LGTM. Build failed due to the long time to run the tests/benches

**Comment by ZER0** [comment]
Let's check with @Fulviuus if we can increase the timeout specifically for this repo / project; or if we can skip some test *only* if we're in travis.

**Comment by CPerezz** [comment]
> Let's check with @Fulviuus if we can increase the timeout specifically for this repo / project; or if we can skip some test _only_ if we're in travis.

I haven't seen this option TBH, but maybe it's possible.
Anyway, we could maybe just ignore the test that is exceeding the time or decrease the degree of the circuit done inside.

Anyway, tests are not running in `relase` mode. Let me fix it and see what happens.

**Comment by vlopes11** [comment]
This travis time limit issue is out of scope of this pull request. I'll proceed with the merge so we can plan the next step (integrate with plonk master)

**Pull request merged**
