### PR TITLE
[WiP] Merkle tree implementation

### PR DESCRIPTION
**Pull request by vlopes11**
Implements #28

### CODE REVIEW

**Comment by vlopes11** [comment]
The changes are minimal before we implement the sponge function

**Comment by ZER0** [comment]
As discussed in person about the naming `sponge_hash` and `merkle_hash`. I'm perfectly fine to have only `sponge` or `merkle`, but only if we add another module. To be clear, I'm fine with both of the following options:

```rust
hades252::scalar::sponge_hash(...)
hades252::linear_combination::sponge_hash(...)
hades252::scalar::markle_hash(...)
hades252::linear_combination::markle_hash(...)
```

or:

```rust
hades252::hash::scalar::sponge(...)
hades252::hash::linear_combination::sponge(...)
hades252::hash::scalar::merkle(...)
hades252::hash::linear_combination::merkle(...)
```

Also, any other combination that works, for example also that is not a bad idea:

```rust
hades252::sponge::scalar::hash(...)
hades252::merkle::scalar::hash(...)
```

Since you might need only one of them – the current version of blind bid doesn't use merkle tree yet, for example.

**Comment by CPerezz** [comment]
> As discussed, let's duplicate the current `hash` function for the `merkle` instead of creating an internal `_hash` with the boolean value.
> 
> So, let's have something like (e.g. for the `Scalar`):
> 
> ```rust
> pub fn sponge_hash(data: &[Scalar]) -> Result<Scalar, PermError> {
>   let width = MDS_MATRIX.len();
> 
>   if data.len() >= width - 1 {
>     return Err(PermError::InputFull);
>   }
> 
>   let mut words = vec![Scalar::zero(); width];
>   let words_slice = &mut words[1..1 + data.len()];
> 
>   words_slice.copy_from_slice(data);  
> 
>   let words = perm(words)?;
>   Ok(words[1])
> }
> ```
> 
> And:
> 
> ```rust
> pub fn merkle_hash(data: &[Scalar]) -> Result<Scalar, PermError> {
>   let width = MDS_MATRIX.len();
> 
>   if data.len() >= width - 1 {
>     return Err(PermError::InputFull);
>   }
> 
>   // The base type declares the output type, so we use u64
>   // since the arity of the merkle tree is not likely to be
>   // >= 2^64.
>   let first_item = Scalar::from((1u64 << data.len()) - 1);
> 
>   let mut words = vec![Scalar::zero(); width];
>   let words_slice = &mut words[1..1 + data.len()];
> 
>   words_slice.copy_from_slice(data);  
>   words[0] = first_item;
> 
>   let words = perm(words)?;
>   Ok(words[1])
> }
> ```
> 
> Since the logic for the `Sponge` would be different, and after the meeting tomorrow the `merkle_hash` would be differ too, so it's good having already some as separate functions.
> 
> (Same for `LinearCombination` ofc)

I don't know if this is the way of performing it.

What I mean is that this performs the hash of only `WIDTH` values, but a whole level of a merkle tree can be bigger, so this function will just be as a `permutation` but not the whole hash of the tree to obtain the root.

**Comment by ZER0** [comment]
Closing as it we're not currently implement the merkle tree for Poseidon.
The relevant code now is https://github.com/dusk-network/dusk-poseidon-merkle

**Pull request closed without merging**
